# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:91627db1-0ae8-4e20-aff8-0c2305f50fd7@git.heroku.com/ticomobackendgit.git
      git push heroku $(Build.SourceBranchName)
